version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=petaloom
      - POSTGRES_PASSWORD=petaloom
      - POSTGRES_DB=petaloom
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: